services:
  db:
    image: postgres:16
    container_name: online_store_db
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U store_user -d store_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: online_store_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: store_db
      DB_USER: store_user
      DB_PASSWORD: store_pass
    ports:
      - "8000:8000"

volumes:
  postgres_data:
